apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tripconnect
  name: postgres-config
data:
  POSTGRES_USER: service
  POSTGRES_PASSWORD: service
  POSTGRES_DB: twofa-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tripconnect
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.4
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  namespace: tripconnect
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
