apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  namespace: tripconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service: "config-service"
        consul.hashicorp.com/connect-service-port: "31070"
        consul.hashicorp.com/transparent-proxy: "true"
    spec:
      containers:
        - name: config-service
          image: ndtrongdev/config-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 31070

---

apiVersion: v1
kind: Service
metadata:
  namespace: tripconnect
  name: config-service
spec:
  selector:
    app: config-service
  ports:
    - port: 31070
      targetPort: 31070
