apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: tripconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service: "gateway-service"
        consul.hashicorp.com/connect-service-port: "31071"
        consul.hashicorp.com/transparent-proxy: "true"
    spec:
      containers:
        - name: gateway-service
          image: ndtrongdev/gateway-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 31071
          env:
            - name: SERVICE_NAME
              value: "gateway-service"
            - name: NODE_ENV
              value: k8s-dev

---

apiVersion: v1
kind: Service
metadata:
  namespace: tripconnect
  name: gateway-service
spec:
  selector:
    app: gateway-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 31071
      targetPort: 31071
      nodePort: 31071
