apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tripconnect
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service: "user-service"
        consul.hashicorp.com/connect-service-port: "31072"
        consul.hashicorp.com/transparent-proxy: "true"
    spec:
      containers:
        - name: user-service
          image: ndtrongdev/user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 31072
          env:
            - name: SERVICE_NAME
              value: "user-service"
            - name: NODE_ENV
              value: k8s-dev

---

apiVersion: v1
kind: Service
metadata:
  namespace: tripconnect
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 31072
      targetPort: 31072
