apiVersion: v1
kind: ConfigMap
metadata:
  name: twofa-config
data:
  POSTGRES_DATABASE: twofa-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twofa-service
  namespace: tripconnect
spec:
  replicas: 3
  selector:
    matchLabels:
      app: twofa-service
  template:
    metadata:
      labels:
        app: twofa-service
    spec:
      containers:
        - name: twofa-service
          image: twofa-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 31073
          envFrom:
            - configMapRef:
                name: application-config
            - configMapRef:
                name: postgres-config
            - configMapRef:
                name: twofa-config
---
apiVersion: v1
kind: Service
metadata:
  name: twofa-service
spec:
  selector:
    app: twofa-service
  ports:
    - protocol: TCP
      port: 31073
      targetPort: 31073
