apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tripconnect
  name: chat-config
data:
  CHAT_SERVICE_PORT: "31073"
  MONGODB_CONNECTION_STRING: mongodb://admin:admin@mongodb:27017/chat-service?authSource=admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: tripconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: chat-service:latest
          imagePullPolicy: Never # Keep as 'Always' for registry
          ports:
            - containerPort: 31072
          envFrom:
            - configMapRef:
                name: application-config
            - configMapRef:
                name: mongodb-config
            - configMapRef:
                name: chat-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: tripconnect
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 31073
      targetPort: 31073
