apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: tripconnect
data:
  GATEWAY_SERVICE_PORT: "31071"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: tripconnect
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: gateway-service:latest
          imagePullPolicy: Never # Keep as 'Always' for registry
          ports:
            - containerPort: 31071
          envFrom:
            - configMapRef:
                name: gateway-config
            - configMapRef:
                name: application-config
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: tripconnect
spec:
  selector:
    app: gateway-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 31071
      targetPort: 31071
      nodePort: 31071
