apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  GATEWAY_SERVICE_PORT: "31071"
  ROUTE_USER_SERVICE: "user-service:31072"
  ROUTE_CHAT_SERVICE: "chat-service:31073"
  ROUTE_TWOFA_SERVICE: "twofa-service:31074"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: tripconnect
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: gateway-service:latest
          imagePullPolicy: Never # Always
          ports:
            - containerPort: 31071
          envFrom:
            - configMapRef:
                name: application-config
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 31071
      targetPort: 31071
      nodePort: 31071
