apiVersion: v1
kind: ConfigMap
metadata:
  name: twofa-config
data:
  TWOFA_SERVICE_PORT: "31074"
  POSTGRES_DATABASE: twofa-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twofa-service
  namespace: tripconnect
spec:
  replicas: 3
  selector:
    matchLabels:
      app: twofa-service
  template:
    metadata:
      labels:
        app: twofa-service
    spec:
      containers:
        - name: twofa-service
          image: twofa-service:latest
          imagePullPolicy: Never # Keep as 'Always' for registry
          ports:
            - containerPort: 31074
          envFrom:
            - configMapRef:
                name: application-config
            - configMapRef:
                name: postgres-config
            - configMapRef:
                name: twofa-config
---
apiVersion: v1
kind: Service
metadata:
  name: twofa-service
spec:
  selector:
    app: twofa-service
  ports:
    - protocol: TCP
      port: 31074
      targetPort: 31074
