apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  USER_SERVICE_PORT: "31072"
  MYSQL_DATABASE: user-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: tripconnect
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 31072
          envFrom:
            - configMapRef:
                name: application-config
            - configMapRef:
                name: mysql-config
            - configMapRef:
                name: user-config
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 31072
      targetPort: 31072
